<?php
// DO NOT EDIT THIS FILE.
header("Access-Control-Allow-Origin: *");

$results = [];

if (isset($_GET['id'])) {
    switch ($_GET['id']) {
        case 1:
            $results = [6, -1, 9.5, 0];
            break;
        case 2:
            $results = [3.8, 5, -8];
            break;
        case 3:
            $results = ['z', 12, '15'];
            break;
        case 4:
            $results = ['a'];
            break;
    }
}

echo json_encode($results, JSON_PRETTY_PRINT);
